// MOCK DATA - Replace with real API calls when backend is ready
// To disable mock data, set USE_MOCK_DATA to false and update API routes to call your backend

export const USE_MOCK_DATA = true // Toggle this to switch between mock and real data

export const mockFreelancerUser = {
  id: "freelancer-1",
  fullName: "John Developer",
  email: "john@example.com",
  phone: "+1-555-0123",
  address: "123 Main Street",
  city: "San Francisco",
  state: "CA",
  zipCode: "94105",
  country: "United States",
  bio: "Experienced full-stack developer with 5+ years of experience in web development",
  skills: ["React", "Node.js", "MongoDB", "TypeScript", "Next.js", "Tailwind CSS"],
  hourlyRate: 75,
  avatar: "/placeholder-user.jpg",
  totalProjects: 12,
  totalEarnings: 45000,
  activeProjects: 3,
}

export const mockProjects = [
  {
    id: "1",
    projectName: "E-commerce Platform",
    projectDescription:
      "Build a full-featured e-commerce platform with payment integration, inventory management, and admin dashboard",
    budget: 5000,
    timeline: "3 months",
    status: "OPEN",
    clientName: "Tech Startup Inc",
    clientEmail: "contact@techstartup.com",
    technologies: ["React", "Node.js", "MongoDB", "Stripe"],
    features: ["Product catalog", "Shopping cart", "Payment processing", "Admin panel"],
    requirements: "Must have experience with e-commerce platforms and payment gateways",
  },
  {
    id: "2",
    projectName: "Mobile App Development",
    projectDescription: "Develop a React Native mobile application for iOS and Android with real-time notifications",
    budget: 8000,
    timeline: "4 months",
    status: "OPEN",
    clientName: "Mobile Solutions Ltd",
    clientEmail: "hello@mobilesolutions.com",
    technologies: ["React Native", "Firebase", "Redux"],
    features: ["Real-time notifications", "User authentication", "Offline support", "Analytics"],
    requirements: "Experience with React Native and mobile app deployment",
  },
  {
    id: "3",
    projectName: "Website Redesign",
    projectDescription: "Redesign existing website with modern UI/UX principles and responsive design",
    budget: 3000,
    timeline: "6 weeks",
    status: "OPEN",
    clientName: "Design Agency Pro",
    clientEmail: "info@designagencypro.com",
    technologies: ["Next.js", "Tailwind CSS", "Figma"],
    features: ["Responsive design", "Modern UI", "SEO optimization", "Performance tuning"],
    requirements: "Strong UI/UX design skills and modern web development knowledge",
  },
  {
    id: "4",
    projectName: "API Development",
    projectDescription: "Create RESTful API for third-party integrations with comprehensive documentation",
    budget: 4000,
    timeline: "2 months",
    status: "OPEN",
    clientName: "Integration Systems",
    clientEmail: "dev@integrationsystems.com",
    technologies: ["Node.js", "Express", "PostgreSQL", "Docker"],
    features: ["REST endpoints", "Authentication", "Rate limiting", "API documentation"],
    requirements: "Backend development expertise and API design knowledge",
  },
  {
    id: "5",
    projectName: "Database Optimization",
    projectDescription: "Optimize existing database queries and structure for better performance",
    budget: 2500,
    timeline: "3 weeks",
    status: "OPEN",
    clientName: "Data Systems Corp",
    clientEmail: "support@datasystemscorp.com",
    technologies: ["PostgreSQL", "MongoDB", "Redis"],
    features: ["Query optimization", "Indexing", "Caching strategy", "Performance monitoring"],
    requirements: "Database administration and optimization experience",
  },
  {
    id: "6",
    projectName: "Cloud Migration",
    projectDescription: "Migrate application to AWS cloud infrastructure with zero downtime",
    budget: 6000,
    timeline: "2 months",
    status: "OPEN",
    clientName: "Cloud Ventures",
    clientEmail: "ops@cloudventures.com",
    technologies: ["AWS", "Docker", "Kubernetes", "CI/CD"],
    features: ["Infrastructure setup", "Auto-scaling", "Load balancing", "Monitoring"],
    requirements: "AWS expertise and DevOps experience required",
  },
]

export const mockProjectStatus = [
  {
    id: "1",
    projectName: "E-commerce Platform",
    projectDescription: "Build a full-featured e-commerce platform",
    status: "IN_PROGRESS",
    currentMilestone: 2,
    totalMilestones: 5,
    progress: 40,
    clientName: "Tech Startup Inc",
    clientEmail: "contact@techstartup.com",
    clientPhone: "+1-555-0456",
    githubLink: "https://github.com/example/ecommerce",
    discordLink: "https://discord.gg/example",
    milestones: [
      { id: 1, name: "Project Setup & Design", status: "COMPLETED" },
      { id: 2, name: "Frontend Development", status: "IN_PROGRESS" },
      { id: 3, name: "Backend API", status: "PENDING" },
      { id: 4, name: "Payment Integration", status: "PENDING" },
      { id: 5, name: "Testing & Deployment", status: "PENDING" },
    ],
  },
  {
    id: "2",
    projectName: "Mobile App Development",
    projectDescription: "Develop a React Native mobile application",
    status: "IN_PROGRESS",
    currentMilestone: 1,
    totalMilestones: 4,
    progress: 25,
    clientName: "Mobile Solutions Ltd",
    clientEmail: "hello@mobilesolutions.com",
    clientPhone: "+1-555-0789",
    githubLink: "https://github.com/example/mobileapp",
    discordLink: "https://discord.gg/example",
    milestones: [
      { id: 1, name: "App Architecture", status: "IN_PROGRESS" },
      { id: 2, name: "UI Implementation", status: "PENDING" },
      { id: 3, name: "Backend Integration", status: "PENDING" },
      { id: 4, name: "Testing & Release", status: "PENDING" },
    ],
  },
  {
    id: "3",
    projectName: "Website Redesign",
    projectDescription: "Redesign existing website",
    status: "COMPLETED",
    currentMilestone: 3,
    totalMilestones: 3,
    progress: 100,
    clientName: "Design Agency Pro",
    clientEmail: "info@designagencypro.com",
    clientPhone: "+1-555-0321",
    githubLink: "https://github.com/example/website",
    discordLink: "https://discord.gg/example",
    milestones: [
      { id: 1, name: "Design & Mockups", status: "COMPLETED" },
      { id: 2, name: "Frontend Development", status: "COMPLETED" },
      { id: 3, name: "Deployment", status: "COMPLETED" },
    ],
  },
]

export const mockBids = [
  {
    id: "1",
    projectName: "E-commerce Platform",
    bidAmount: 4500,
    bidDate: "2024-01-15",
    status: "PENDING",
    projectId: "1",
  },
  {
    id: "2",
    projectName: "Mobile App Development",
    bidAmount: 7500,
    bidDate: "2024-01-14",
    status: "ACCEPTED",
    projectId: "2",
  },
  {
    id: "3",
    projectName: "Website Redesign",
    bidAmount: 2800,
    bidDate: "2024-01-13",
    status: "PENDING",
    projectId: "3",
  },
  {
    id: "4",
    projectName: "API Development",
    bidAmount: 3800,
    bidDate: "2024-01-12",
    status: "REJECTED",
    projectId: "4",
  },
  {
    id: "5",
    projectName: "Database Optimization",
    bidAmount: 2300,
    bidDate: "2024-01-11",
    status: "PENDING",
    projectId: "5",
  },
  {
    id: "6",
    projectName: "Cloud Migration",
    bidAmount: 5500,
    bidDate: "2024-01-10",
    status: "ACCEPTED",
    projectId: "6",
  },
  {
    id: "7",
    projectName: "UI/UX Design",
    bidAmount: 3200,
    bidDate: "2024-01-09",
    status: "PENDING",
    projectId: "7",
  },
  {
    id: "8",
    projectName: "SEO Optimization",
    bidAmount: 1800,
    bidDate: "2024-01-08",
    status: "ACCEPTED",
    projectId: "8",
  },
  {
    id: "9",
    projectName: "Content Management System",
    bidAmount: 4200,
    bidDate: "2024-01-07",
    status: "PENDING",
    projectId: "9",
  },
  {
    id: "10",
    projectName: "Security Audit",
    bidAmount: 3500,
    bidDate: "2024-01-06",
    status: "PENDING",
    projectId: "10",
  },
]
