// MOCK DATA - Replace with real API calls when backend is ready
// To disable mock data, set USE_MOCK_DATA to false and update API routes to call your backend

export const USE_MOCK_DATA = true // Toggle this to switch between mock and real data

export const mockFreelancerUser = {
  id: "freelancer-1",
  fullName: "John Developer",
  email: "john@example.com",
  phone: "+1-555-0123",
  address: "123 Main Street",
  city: "San Francisco",
  state: "CA",
  zipCode: "94105",
  country: "United States",
  bio: "Experienced full-stack developer with 5+ years of experience in web development, specializing in React, Node.js, and cloud technologies.",
  skills: ["React", "Node.js", "MongoDB", "TypeScript", "Next.js", "Tailwind CSS", "AWS", "Docker", "PostgreSQL"],
  hourlyRate: 75,
  avatar: "/placeholder-user.jpg",
  totalProjects: 12,
  totalEarnings: 45000,
  activeProjects: 3,
  completedProjects: 9,
  averageRating: 4.8,
  totalReviews: 24,
  joinDate: "2022-03-15",
  portfolio: "https://johndeveloper.com",
  github: "https://github.com/johndeveloper",
  linkedin: "https://linkedin.com/in/johndeveloper",
}

export const mockProjects = [
  {
    id: "1",
    projectName: "E-commerce Platform",
    projectDescription:
      "Build a full-featured e-commerce platform with payment integration, inventory management, and admin dashboard. The platform should support multiple payment gateways, real-time inventory tracking, and comprehensive analytics.",
    budget: 5000,
    timeline: "3 months",
    status: "OPEN",
    clientName: "Tech Startup Inc",
    clientEmail: "contact@techstartup.com",
    clientPhone: "+1-555-0456",
    clientCompany: "Tech Startup Inc",
    technologies: ["React", "Node.js", "MongoDB", "Stripe", "AWS"],
    features: [
      "Product catalog with search and filters",
      "Shopping cart and checkout",
      "Payment processing with Stripe",
      "Admin panel for inventory management",
      "User authentication and profiles",
      "Order tracking and history",
      "Email notifications",
      "Analytics dashboard",
    ],
    requirements:
      "Must have experience with e-commerce platforms and payment gateways. Experience with AWS and scalable architecture is a plus.",
    deliverables: ["Complete source code", "API documentation", "Deployment guide", "User manual", "Admin guide"],
    attachments: ["requirements.pdf", "wireframes.figma"],
    createdDate: "2024-01-20",
    deadline: "2024-04-20",
    proposalCount: 12,
  },
  {
    id: "2",
    projectName: "Mobile App Development",
    projectDescription:
      "Develop a React Native mobile application for iOS and Android with real-time notifications, offline support, and seamless user experience. The app should include user authentication, push notifications, and offline data sync.",
    budget: 8000,
    timeline: "4 months",
    status: "OPEN",
    clientName: "Mobile Solutions Ltd",
    clientEmail: "hello@mobilesolutions.com",
    clientPhone: "+1-555-0789",
    clientCompany: "Mobile Solutions Ltd",
    technologies: ["React Native", "Firebase", "Redux", "Expo"],
    features: [
      "User authentication with social login",
      "Real-time notifications",
      "Offline data synchronization",
      "Push notifications",
      "Analytics integration",
      "In-app messaging",
      "User profiles and settings",
      "Payment integration",
    ],
    requirements:
      "Experience with React Native and mobile app deployment on both iOS and Android. Firebase experience is required.",
    deliverables: [
      "iOS and Android apps",
      "Source code repository",
      "App store submission guide",
      "Testing report",
      "Maintenance documentation",
    ],
    attachments: ["app-mockups.figma", "technical-spec.pdf"],
    createdDate: "2024-01-18",
    deadline: "2024-05-18",
    proposalCount: 8,
  },
  {
    id: "3",
    projectName: "Website Redesign",
    projectDescription:
      "Redesign existing website with modern UI/UX principles and responsive design. The new design should improve user engagement, reduce bounce rate, and improve SEO performance.",
    budget: 3000,
    timeline: "6 weeks",
    status: "OPEN",
    clientName: "Design Agency Pro",
    clientEmail: "info@designagencypro.com",
    clientPhone: "+1-555-0321",
    clientCompany: "Design Agency Pro",
    technologies: ["Next.js", "Tailwind CSS", "Figma", "Vercel"],
    features: [
      "Responsive design for all devices",
      "Modern and clean UI",
      "SEO optimization",
      "Performance optimization",
      "Accessibility compliance",
      "Contact form integration",
      "Blog section",
      "Analytics integration",
    ],
    requirements:
      "Strong UI/UX design skills and modern web development knowledge. Experience with Next.js and Tailwind CSS is required.",
    deliverables: [
      "Responsive website",
      "Design system documentation",
      "Performance report",
      "SEO audit",
      "Deployment guide",
    ],
    attachments: ["current-site-analysis.pdf", "design-inspiration.pdf"],
    createdDate: "2024-01-22",
    deadline: "2024-03-05",
    proposalCount: 15,
  },
  {
    id: "4",
    projectName: "API Development",
    projectDescription:
      "Create RESTful API for third-party integrations with comprehensive documentation. The API should be scalable, secure, and well-documented with rate limiting and authentication.",
    budget: 4000,
    timeline: "2 months",
    status: "OPEN",
    clientName: "Integration Systems",
    clientEmail: "dev@integrationsystems.com",
    clientPhone: "+1-555-0654",
    clientCompany: "Integration Systems",
    technologies: ["Node.js", "Express", "PostgreSQL", "Docker", "JWT"],
    features: [
      "RESTful endpoints",
      "JWT authentication",
      "Rate limiting",
      "API versioning",
      "Comprehensive documentation",
      "Error handling",
      "Logging and monitoring",
      "Unit and integration tests",
    ],
    requirements:
      "Backend development expertise and API design knowledge. Experience with PostgreSQL and Docker is required.",
    deliverables: [
      "API source code",
      "API documentation (Swagger/OpenAPI)",
      "Postman collection",
      "Deployment guide",
      "Test coverage report",
    ],
    attachments: ["api-requirements.pdf", "database-schema.sql"],
    createdDate: "2024-01-19",
    deadline: "2024-03-19",
    proposalCount: 6,
  },
  {
    id: "5",
    projectName: "Database Optimization",
    projectDescription:
      "Optimize existing database queries and structure for better performance. Analyze current queries, implement indexing strategies, and improve overall database efficiency.",
    budget: 2500,
    timeline: "3 weeks",
    status: "OPEN",
    clientName: "Data Systems Corp",
    clientEmail: "support@datasystemscorp.com",
    clientPhone: "+1-555-0987",
    clientCompany: "Data Systems Corp",
    technologies: ["PostgreSQL", "MongoDB", "Redis", "Query Analyzer"],
    features: [
      "Query optimization",
      "Index creation and optimization",
      "Caching strategy implementation",
      "Performance monitoring setup",
      "Database cleanup",
      "Backup optimization",
      "Replication setup",
    ],
    requirements:
      "Database administration and optimization experience. Experience with both SQL and NoSQL databases is preferred.",
    deliverables: [
      "Optimization report",
      "Query analysis",
      "Index recommendations",
      "Performance benchmarks",
      "Maintenance guide",
    ],
    attachments: ["current-queries.sql", "performance-metrics.csv"],
    createdDate: "2024-01-21",
    deadline: "2024-02-11",
    proposalCount: 4,
  },
  {
    id: "6",
    projectName: "Cloud Migration",
    projectDescription:
      "Migrate application to AWS cloud infrastructure with zero downtime. Set up auto-scaling, load balancing, and implement CI/CD pipeline for continuous deployment.",
    budget: 6000,
    timeline: "2 months",
    status: "OPEN",
    clientName: "Cloud Ventures",
    clientEmail: "ops@cloudventures.com",
    clientPhone: "+1-555-1234",
    clientCompany: "Cloud Ventures",
    technologies: ["AWS", "Docker", "Kubernetes", "Terraform", "Jenkins"],
    features: [
      "Infrastructure as Code setup",
      "Auto-scaling configuration",
      "Load balancing",
      "CI/CD pipeline",
      "Monitoring and alerting",
      "Backup and disaster recovery",
      "Security hardening",
      "Cost optimization",
    ],
    requirements: "AWS expertise and DevOps experience required. Experience with Kubernetes and Terraform is a plus.",
    deliverables: [
      "AWS infrastructure setup",
      "Terraform code",
      "CI/CD pipeline configuration",
      "Monitoring dashboard",
      "Migration guide",
      "Cost analysis report",
    ],
    attachments: ["current-infrastructure.pdf", "migration-plan.pdf"],
    createdDate: "2024-01-17",
    deadline: "2024-03-17",
    proposalCount: 5,
  },
]

export const mockProjectStatus = [
  {
    id: "1",
    projectName: "E-commerce Platform",
    projectDescription: "Build a full-featured e-commerce platform with payment integration",
    status: "IN_PROGRESS",
    currentMilestone: 2,
    totalMilestones: 5,
    progress: 40,
    clientName: "Tech Startup Inc",
    clientEmail: "contact@techstartup.com",
    clientPhone: "+1-555-0456",
    clientAvatar: "/placeholder-user.jpg",
    githubLink: "https://github.com/example/ecommerce",
    discordLink: "https://discord.gg/example",
    paymentStatus: "PARTIAL",
    amountPaid: 2000,
    totalAmount: 5000,
    startDate: "2024-01-20",
    expectedEndDate: "2024-04-20",
    milestones: [
      {
        id: 1,
        name: "Project Setup & Design",
        status: "COMPLETED",
        completedDate: "2024-01-27",
        payment: 1000,
      },
      {
        id: 2,
        name: "Frontend Development",
        status: "IN_PROGRESS",
        progress: 60,
        expectedDate: "2024-02-24",
        payment: 1000,
      },
      {
        id: 3,
        name: "Backend API",
        status: "PENDING",
        expectedDate: "2024-03-10",
        payment: 1000,
      },
      {
        id: 4,
        name: "Payment Integration",
        status: "PENDING",
        expectedDate: "2024-03-24",
        payment: 1000,
      },
      {
        id: 5,
        name: "Testing & Deployment",
        status: "PENDING",
        expectedDate: "2024-04-20",
        payment: 1000,
      },
    ],
    updates: [
      {
        date: "2024-02-10",
        message: "Frontend development 60% complete. UI components implemented.",
      },
      {
        date: "2024-02-05",
        message: "Design phase completed. All mockups approved by client.",
      },
      {
        date: "2024-01-27",
        message: "Project setup completed. Development environment ready.",
      },
    ],
  },
  {
    id: "2",
    projectName: "Mobile App Development",
    projectDescription: "Develop a React Native mobile application for iOS and Android",
    status: "IN_PROGRESS",
    currentMilestone: 1,
    totalMilestones: 4,
    progress: 25,
    clientName: "Mobile Solutions Ltd",
    clientEmail: "hello@mobilesolutions.com",
    clientPhone: "+1-555-0789",
    clientAvatar: "/placeholder-user.jpg",
    githubLink: "https://github.com/example/mobileapp",
    discordLink: "https://discord.gg/example",
    paymentStatus: "PARTIAL",
    amountPaid: 2000,
    totalAmount: 8000,
    startDate: "2024-01-18",
    expectedEndDate: "2024-05-18",
    milestones: [
      {
        id: 1,
        name: "App Architecture & Setup",
        status: "IN_PROGRESS",
        progress: 80,
        expectedDate: "2024-02-15",
        payment: 2000,
      },
      {
        id: 2,
        name: "UI Implementation",
        status: "PENDING",
        expectedDate: "2024-03-15",
        payment: 2000,
      },
      {
        id: 3,
        name: "Backend Integration",
        status: "PENDING",
        expectedDate: "2024-04-15",
        payment: 2000,
      },
      {
        id: 4,
        name: "Testing & Release",
        status: "PENDING",
        expectedDate: "2024-05-18",
        payment: 2000,
      },
    ],
    updates: [
      {
        date: "2024-02-08",
        message: "App architecture finalized. Redux store setup completed.",
      },
      {
        date: "2024-02-01",
        message: "Project kickoff meeting completed. Development started.",
      },
    ],
  },
  {
    id: "3",
    projectName: "Website Redesign",
    projectDescription: "Redesign existing website with modern UI/UX principles",
    status: "COMPLETED",
    currentMilestone: 3,
    totalMilestones: 3,
    progress: 100,
    clientName: "Design Agency Pro",
    clientEmail: "info@designagencypro.com",
    clientPhone: "+1-555-0321",
    clientAvatar: "/placeholder-user.jpg",
    githubLink: "https://github.com/example/website",
    discordLink: "https://discord.gg/example",
    paymentStatus: "COMPLETED",
    amountPaid: 3000,
    totalAmount: 3000,
    startDate: "2024-01-22",
    expectedEndDate: "2024-03-05",
    completedDate: "2024-03-03",
    milestones: [
      {
        id: 1,
        name: "Design & Mockups",
        status: "COMPLETED",
        completedDate: "2024-02-05",
        payment: 1000,
      },
      {
        id: 2,
        name: "Frontend Development",
        status: "COMPLETED",
        completedDate: "2024-02-26",
        payment: 1000,
      },
      {
        id: 3,
        name: "Deployment & Launch",
        status: "COMPLETED",
        completedDate: "2024-03-03",
        payment: 1000,
      },
    ],
    updates: [
      {
        date: "2024-03-03",
        message: "Website successfully deployed to production. All systems operational.",
      },
      {
        date: "2024-02-26",
        message: "Frontend development completed. Ready for deployment.",
      },
      {
        date: "2024-02-05",
        message: "Design phase completed. All mockups approved by client.",
      },
    ],
    clientReview: {
      rating: 5,
      comment: "Excellent work! The new design exceeded our expectations. Highly recommended!",
    },
  },
  {
    id: "4",
    projectName: "API Development",
    projectDescription: "Create RESTful API for third-party integrations",
    status: "IN_PROGRESS",
    currentMilestone: 2,
    totalMilestones: 4,
    progress: 50,
    clientName: "Integration Systems",
    clientEmail: "dev@integrationsystems.com",
    clientPhone: "+1-555-0654",
    clientAvatar: "/placeholder-user.jpg",
    githubLink: "https://github.com/example/api",
    discordLink: "https://discord.gg/example",
    paymentStatus: "PARTIAL",
    amountPaid: 2000,
    totalAmount: 4000,
    startDate: "2024-01-19",
    expectedEndDate: "2024-03-19",
    milestones: [
      {
        id: 1,
        name: "API Design & Setup",
        status: "COMPLETED",
        completedDate: "2024-02-02",
        payment: 1000,
      },
      {
        id: 2,
        name: "Core Endpoints Development",
        status: "IN_PROGRESS",
        progress: 70,
        expectedDate: "2024-02-23",
        payment: 1000,
      },
      {
        id: 3,
        name: "Testing & Documentation",
        status: "PENDING",
        expectedDate: "2024-03-09",
        payment: 1000,
      },
      {
        id: 4,
        name: "Deployment & Support",
        status: "PENDING",
        expectedDate: "2024-03-19",
        payment: 1000,
      },
    ],
    updates: [
      {
        date: "2024-02-10",
        message: "Core endpoints 70% complete. Authentication implemented.",
      },
      {
        date: "2024-02-02",
        message: "API design finalized. Database schema approved.",
      },
    ],
  },
]

export const mockBids = [
  {
    id: "1",
    projectName: "E-commerce Platform",
    bidAmount: 4500,
    bidDate: "2024-01-20",
    status: "PENDING",
    projectId: "1",
    bidMessage:
      "I have extensive experience with e-commerce platforms and have successfully delivered similar projects. I can complete this within the timeline.",
    freelancerName: "John Developer",
    freelancerRating: 4.8,
    freelancerProjects: 12,
  },
  {
    id: "2",
    projectName: "Mobile App Development",
    bidAmount: 7500,
    bidDate: "2024-01-18",
    status: "ACCEPTED",
    projectId: "2",
    bidMessage:
      "React Native expert with 5+ years of experience. I have built multiple apps for iOS and Android. Ready to start immediately.",
    freelancerName: "John Developer",
    freelancerRating: 4.8,
    freelancerProjects: 12,
  },
  {
    id: "3",
    projectName: "Website Redesign",
    bidAmount: 2800,
    bidDate: "2024-01-22",
    status: "PENDING",
    projectId: "3",
    bidMessage:
      "Modern web design specialist. I can deliver a beautiful, responsive website that improves user engagement and SEO.",
    freelancerName: "John Developer",
    freelancerRating: 4.8,
    freelancerProjects: 12,
  },
  {
    id: "4",
    projectName: "API Development",
    bidAmount: 3800,
    bidDate: "2024-01-19",
    status: "REJECTED",
    projectId: "4",
    bidMessage: "Backend development expert. I can create a scalable, well-documented API with comprehensive testing.",
    freelancerName: "John Developer",
    freelancerRating: 4.8,
    freelancerProjects: 12,
  },
  {
    id: "5",
    projectName: "Database Optimization",
    bidAmount: 2300,
    bidDate: "2024-01-21",
    status: "PENDING",
    projectId: "5",
    bidMessage:
      "Database optimization specialist. I can improve query performance and implement efficient caching strategies.",
    freelancerName: "John Developer",
    freelancerRating: 4.8,
    freelancerProjects: 12,
  },
  {
    id: "6",
    projectName: "Cloud Migration",
    bidAmount: 5500,
    bidDate: "2024-01-17",
    status: "ACCEPTED",
    projectId: "6",
    bidMessage:
      "AWS certified DevOps engineer. I have successfully migrated multiple applications to AWS with zero downtime.",
    freelancerName: "John Developer",
    freelancerRating: 4.8,
    freelancerProjects: 12,
  },
  {
    id: "7",
    projectName: "UI/UX Design",
    bidAmount: 3200,
    bidDate: "2024-01-16",
    status: "PENDING",
    projectId: "7",
    bidMessage:
      "Creative UI/UX designer with portfolio of successful projects. I focus on user-centered design principles.",
    freelancerName: "John Developer",
    freelancerRating: 4.8,
    freelancerProjects: 12,
  },
  {
    id: "8",
    projectName: "SEO Optimization",
    bidAmount: 1800,
    bidDate: "2024-01-15",
    status: "ACCEPTED",
    projectId: "8",
    bidMessage: "SEO expert with proven track record of improving search rankings. I use white-hat techniques only.",
    freelancerName: "John Developer",
    freelancerRating: 4.8,
    freelancerProjects: 12,
  },
  {
    id: "9",
    projectName: "Content Management System",
    bidAmount: 4200,
    bidDate: "2024-01-14",
    status: "PENDING",
    projectId: "9",
    bidMessage:
      "CMS development specialist. I can build a custom CMS tailored to your specific needs with easy-to-use interface.",
    freelancerName: "John Developer",
    freelancerRating: 4.8,
    freelancerProjects: 12,
  },
  {
    id: "10",
    projectName: "Security Audit",
    bidAmount: 3500,
    bidDate: "2024-01-13",
    status: "PENDING",
    projectId: "10",
    bidMessage:
      "Security expert with experience in penetration testing and vulnerability assessment. I provide comprehensive security audits.",
    freelancerName: "John Developer",
    freelancerRating: 4.8,
    freelancerProjects: 12,
  },
]

export const mockContactSubmissions = [
  {
    id: "1",
    name: "Alice Johnson",
    email: "alice@example.com",
    phone: "+1-555-1111",
    subject: "Project Inquiry",
    message: "I have a new project and would like to discuss the details with you.",
    submittedDate: "2024-02-10",
    status: "NEW",
  },
  {
    id: "2",
    name: "Bob Smith",
    email: "bob@example.com",
    phone: "+1-555-2222",
    subject: "Collaboration Opportunity",
    message: "We would like to collaborate on an upcoming project. Please get back to us.",
    submittedDate: "2024-02-09",
    status: "REPLIED",
  },
  {
    id: "3",
    name: "Carol White",
    email: "carol@example.com",
    phone: "+1-555-3333",
    subject: "Technical Support",
    message: "I need help with integrating your API into my application.",
    submittedDate: "2024-02-08",
    status: "RESOLVED",
  },
]
